#!/usr/bin/env bash
set -euo pipefail

# installing chromium browser to enable webpdf conversion using nbconvert
export PLAYWRIGHT_BROWSERS_PATH=${CONDA_DIR}
playwright install chromium

# https://github.com/berkeley-dsep-infra/datahub/issues/5827
git config --system pull.rebase false
      for notebook in image-tests/*.ipynb; do
          jupyter nbconvert --to webpdf "$notebook"
          if [ ! -f "${notebook%.ipynb}.pdf" ]; then
              echo "Error: PDF conversion failed for $notebook"
              exit 1
          fi
      done
